# General Jekyll Stuff
title: katie's home
description: Hey...
twitter_username: katebuilder
github_username:  katiebuilder

# Theme
remote_theme: just-the-docs/just-the-docs
# Theme config
color_scheme: dark
search:
  button: true
aux_links:
  GitHub: https://github.com/katiebuilder/katiebuilder/tree/gh-pages
nav_external_links:
  - title: Discord Server
    url: https://discord.com/invite/s2MqCGVZyS
    hide_icon: false
  - title: Admission Form
    url: https://docs.google.com/forms/d/e/1FAIpQLSerXeibIQ-2X7JWN0h2sES5b2EIpOA_LPF4DvWRjM7UviLbOQ/viewform
    hide_icon: false
  - title: pronouns.page
    url: https://en.pronouns.page/@katebuilds
    hide_icon: false
