# General Jekyll Stuff
title: KeatonBuilder
description: Hey...
twitter_username: keatonbuilder
github_username:  keatonbuilder

# Theme
remote_theme: just-the-docs/just-the-docs
# Theme config
color_scheme: dark
search:
  button: true
aux_links:
  GitHub: https://github.com/keatonbuilder/keatonbuilder/tree/gh-pages
nav_external_links:
  - title: pronouns.page
    url: https://pronouns.page/@keatonbuilds
    hide_icon: false